### ISSUE TITLE
xgorgon full source

### ISSUE THREAD

**Issue by DerTechs** [tiktokmate/X-Gorgon-X-Khronos-Tik-Tok#1]
full source code to generate xgorgon and xkhronos headers! very cheap for the first 3 buyers! email me at Contact for demo and token: https://t.me/meandmyrule

**Comment by gongxufan** [comment]
email please,i will contact with u.

**Comment by DerTechs** [comment]
xgorgon@protonmail.com

**Comment by demon071** [comment]
Price?

**Comment by xgorgon** [comment]
Usd400 if you buy today contact me on telegram @adotdaniel

**Comment by demon071** [comment]
update lifietime and support douyin, tiktok

**Comment by xgorgon** [comment]
Yes

**Comment by tiktokmate** [comment]
connect on telegram https://t.me/meandmyrule
